### ISSUE TITLE
Do not use container-syntax for volume mounts

### ISSUE THREAD

**Issue by EugenMayer** [timglabisch/symfony_docker_sync#2]
Interesting boilerplate you have here, good work.

Since you are using docker-sync and probably used an older boilerplate, we improved something.

You should no longer use container-name based mounts https://github.com/timglabisch/symfony_docker_sync/blob/master/docker-compose-dev.yml#L5, this leads to issues like this on cleaning: https://github.com/EugenMayer/docker-sync/issues/182

Instead use volume-name based mounts https://github.com/EugenMayer/docker-sync-boilerplate/blob/master/simplest/docker-compose-dev.yml#L8

This will help you but also bring you a step further, since container-named volume mounts are deprecated in docker, since volume name mounts have been introduced

**Comment by EugenMayer** [comment]
Probably interesting https://github.com/EugenMayer/docker-sync/issues/116

**Comment by timglabisch** [comment]
interesting, this repo was just a quick try - i don't really use it.
i'll keep this issue open and may if i've some time i'll take a closer look.

but feel free to create a PR.
